import { SketchAnalysisResult } from '../types';
import { APP_NAME, APP_VERSION } from '../shared/aiSpec';
import { createZip, type ZipEntry } from './zip';

function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'architecture'
  );
}

function buildReadme(result: SketchAnalysisResult): string {
  const bullets = (items: string[]) => (items.length ? items.map((i) => `- ${i}`).join('\n') : '_None reported._');

  const plan = result.implementation_plan.length
    ? result.implementation_plan
        .map((s) => `${s.step}. **${s.task}**${s.file_affected ? ` (\`${s.file_affected}\`)` : ''}\n   ${s.description}`)
        .join('\n')
    : '_No plan generated._';

  const nodes = result.nodes.length
    ? [
        '| Component | Type | Tech | Port |',
        '| --- | --- | --- | --- |',
        ...result.nodes.map(
          (n) => `| ${n.label} | ${n.type} | ${n.tech} | ${n.details.port ?? '—'} |`,
        ),
      ].join('\n')
    : '_No components detected._';

  return `# ${result.title}

${result.summary}

> Generated by ${APP_NAME} v${APP_VERSION}. Confidence: ${(result.confidence * 100).toFixed(0)}% · Handwriting clarity: ${result.handwriting_clarity}

## Components

${nodes}

## Architecture review

### Strengths
${bullets(result.architecture_review.strengths)}

### Issues
${bullets(result.architecture_review.issues)}

### Recommendations
${bullets(result.architecture_review.recommendations)}

## Implementation plan

${plan}

## Files

- \`infrastructure.yaml\` — generated infrastructure config
- \`docker-compose.yml\` — generated compose file
- \`architecture.mmd\` — Mermaid source for the topology diagram
- \`architecture.json\` — the full structured analysis
`;
}

export function buildExportEntries(result: SketchAnalysisResult): ZipEntry[] {
  const entries: ZipEntry[] = [
    { name: 'README.md', content: buildReadme(result) },
    { name: 'architecture.json', content: JSON.stringify(result, null, 2) },
  ];

  if (result.generated_code_snippets.infrastructure_yaml) {
    entries.push({ name: 'infrastructure.yaml', content: result.generated_code_snippets.infrastructure_yaml });
  }
  if (result.generated_code_snippets.docker_compose) {
    entries.push({ name: 'docker-compose.yml', content: result.generated_code_snippets.docker_compose });
  }
  if (result.generated_code_snippets.api_schema) {
    entries.push({ name: 'api-schema.yaml', content: result.generated_code_snippets.api_schema });
  }
  if (result.mermaid) {
    entries.push({ name: 'architecture.mmd', content: result.mermaid });
  }

  return entries;
}

/**
 * Packages the generated artifacts and hands the browser a real download.
 * Returns the filename so the caller can report what actually happened.
 */
export function exportAnalysis(result: SketchAnalysisResult): string {
  const entries = buildExportEntries(result);
  const blob = createZip(entries);
  const filename = `${slugify(result.title)}.zip`;

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Revoking synchronously can cancel the download in some browsers.
  window.setTimeout(() => URL.revokeObjectURL(url), 10_000);

  return filename;
}
